name: twitter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.1.2
  flutter_bloc: ^8.1.3
  mask_text_input_formatter: ^2.4.0
  sqflite: ^2.3.0
  dio: ^5.3.2
  get_it: ^7.6.4
  lottie: ^2.6.0
  image_picker: ^1.0.1
  pinput: ^3.0.0
  cached_network_image: ^3.2.3
  like_button: ^2.0.5
  equatable: ^2.0.5
  url_launcher: ^6.1.12
  flutter_linkify: ^6.0.0
  keyboard_dismisser: ^3.0.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/lottie/